import { Job } from '../types/Job';

export const MOCK_JOBS: Job[] = [
  {
    id: '1',
    title: 'Senior Actuarial Analyst',
    company: 'Global Life Insurance',
    location: 'London, UK',
    posting_date: '2025-10-15',
    job_type: 'Full-time',
    tags: ['Life', 'Pricing', 'Python', 'Fellow'],
  },
  {
    id: '2',
    title: 'Junior Health Actuary',
    company: 'HealthCare Solutions',
    location: 'New York, USA',
    posting_date: '2025-10-18',
    job_type: 'Full-time',
    tags: ['Health', 'Entry-Level', 'Analytics'],
  },
  {
    id: '3',
    title: 'Actuarial Intern',
    company: 'Pension Fund Associates',
    location: 'Toronto, Canada',
    posting_date: '2025-10-20',
    job_type: 'Internship',
    tags: ['Pensions', 'Student', 'Modeling'],
  },
  {
    id: '4',
    title: 'Pricing Actuary',
    company: 'InsureTech Innovations',
    location: 'Remote',
    posting_date: '2025-10-12',
    job_type: 'Full-time',
    tags: ['Pricing', 'Life', 'R', 'Associate'],
  },
  {
    id: '5',
    title: 'Reserving Actuary',
    company: 'Property & Casualty Group',
    location: 'Chicago, USA',
    posting_date: '2025-10-10',
    job_type: 'Full-time',
    tags: ['Reserving', 'P&C', 'Excel', 'Fellow'],
  },
  {
    id: '6',
    title: 'Data Science Actuary',
    company: 'Analytics First Insurance',
    location: 'San Francisco, USA',
    posting_date: '2025-10-22',
    job_type: 'Full-time',
    tags: ['Data Science', 'Python', 'Machine Learning', 'Health'],
  },
  {
    id: '7',
    title: 'Part-Time Actuarial Consultant',
    company: 'Consulting Actuaries Ltd',
    location: 'Sydney, Australia',
    posting_date: '2025-10-14',
    job_type: 'Part-time',
    tags: ['Consulting', 'Life', 'Health'],
  },
  {
    id: '8',
    title: 'Investment Actuary',
    company: 'Wealth Management Corp',
    location: 'Singapore',
    posting_date: '2025-10-19',
    job_type: 'Full-time',
    tags: ['Investments', 'Asset Liability', 'Risk Management'],
  },
];
